name: Unit tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -e .
    - name: Install test dependencies
      working-directory: tests
      run: |
        sudo apt install libopenblas-dev # scipy
        pip install -r requirements.txt
    - name: Test with pytest
      working-directory: tests
      run: |
        pytest .
